django_til/MN practice/crud/accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('<username>/',views.profile, name='profile')
]

django_til/MN practice/crud/articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/like/', views.like, name='like')
]

django_til/MN practice/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<username>/follow/', views.follow, name='follow'),
]

django_til/MN practice/crud/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='followings',

    )

django_til/MN practice/crud/articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 목적어가 되는 모델에 주로 정의를 함
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_articles',
    )

django_til/MN practice/crud/articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article 
        exclude = ['created_at', 'updated_at', 'user',]

django_til/MN practice/crud/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from .form import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import get_user_model

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('articles:index')

def follow(request,username):
    person = get_object_or_404(get_user_model(),username=username)
    if request.user in person.followers.all():
        person.followers.remove(request.user)
    else:
        person.followers.add(request.user)
    return redirect('accounts:profile', person.username)

def profile(request,username):
    User = get_user_model()
    person = get_object_or_404(User,username=username)
    context = {'person':person}
    return render(request,'accounts/profile.html',context)

django_til/MN practice/crud/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/form.html', context)

@login_required
def like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
    else :
        article.like_users.add(request.user)
        print(Article.objects.filter(user=request.user))

    return redirect('articles:index')

django_til/MN practice/crud/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>LOGIN</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
  </form>
  <a href="{% url 'articles:index' %}">INDEX</a>
{% endblock %}

django_til/MN practice/crud/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{ person.username }}님의 프로필</h1>
  <p>팔로워 : {{ person.followers.count }}명</p>
  <p>팔로잉 : {{ person.followings.count }}명</p>
  {% if request.user in person.followers.all %}
    <a href="{% url 'follow' person.username %}"><i class="fas fa-heart">언팔로우</i></a>
  {% else %}
    <a href="{% url 'follow' person.username %}"><i class="far fa-heart">팔로우</i></a>
  {% endif %}

  {% for article in person.article_set.all %}
    <h2>{{ person.username }}님이 작성한 글</h2>
    <p>제목 :{{ article.title }}</p>
    <p>좋아여 : {{ article.like_users.all.count }}</p>
    <p>내용 : {{ article.content }}</p>
  {% endfor %}
{% endblock %}

django_til/MN practice/crud/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>SIGNUP</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
  </form>
  <a href="{% url 'articles:index' %}">INDEX</a>
{% endblock %}

django_til/MN practice/crud/articles/templates/articles/form.html
{% extends 'base.html' %}

{% block content %}
  <h2>CREATE</h2>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">INDEX</a>
{% endblock %}

django_til/MN practice/crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h2>INDEX</h2>
  <a href="{% url 'articles:create' %}">NEW</a>
  {% for article in articles %}
    <ul>
      <li>{{ article.user }}의 {{ article.pk }}번글</li>
      <li>제목: {{ article.title }}</li>
      <li>내용: {{ article.content }}</li>
      <li>{% include 'articles/like.html' %}</li>
    </ul>
    <hr>
  {% endfor %}
{% endblock %}

django_til/MN practice/crud/articles/templates/articles/like.html
{% if request.user in article.like_users.all %}
  <a href="{% url 'articles:like' article.pk %}"><i class="fas fa-heart">취소</i></a>
{% else %}
  <a href="{% url 'articles:like' article.pk %}"><i class="far fa-heart">좋아요</i></a>
{% endif %}
<p>{{ article.like_users.count }}</p>

django_til/MN practice/crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://kit.fontawesome.com/e4c1cde6dc.js" crossorigin="anonymous"></script>
  <title>exercise</title>
</head>
<body>
  <h1>Articles</h1>
  {% if user.is_authenticated %}
    <h2>{{ user.username }}님 안녕하세요!</h2>
    <a href="{% url 'accounts:logout' %}">LOGOUT</a>
  {% else %}
    <a href="{% url 'accounts:login' %}">LOGIN</a>
    <a href="{% url 'accounts:signup' %}">SIGNUP</a>
  {% endif %}
  <hr>
  {% block content %}
  {% endblock %}
</body>
</html>